### ISSUE TITLE
Read source codes of problem 2, 3, 4

### ISSUE THREAD

**Issue by hydrop** [hydrop/ProjectEuler#1]
They are written in Fortran.
What language are you using @sunjungyup?

**Comment by sunjungyup** [comment]
이거 여기에 쓰는거 맞나요??

**Comment by hydrop** [comment]
ㅎㅎ 한글로 써도 되네

**Comment by sunjungyup** [comment]
ㅎㅎㅎ

**Comment by hydrop** [comment]
언어는 어떤 거 사용하고 있어?

**Comment by sunjungyup** [comment]
c언어 사용하고 있기는 한데 너무 초보적이라 사용한다고 하기도 좀 그랴요

**Comment by hydrop** [comment]
순수 C 아님 C++?
이외에는 사용해 본 적이 없어?

**Comment by sunjungyup** [comment]
순수 c인거 같고요 아두이노 써보기는 했는데 컴퓨터 명령어랑 너무 달라서 못쓸거같아요

**Comment by hydrop** [comment]
C는 좀 어려울 수 있긴 한데...
아두이노는 검색해 보니 C++ 문법인거 같네

**Comment by sunjungyup** [comment]
그런가요?? 제가 잘 몰라서ㅎㅎ

**Comment by sunjungyup** [comment]
3번빼고는 명령어 찾아보면서 이해한거같은데 3번 함수명령어는 이해가 안돼요

**Comment by hydrop** [comment]
지금은 이해 안 되어도 괜찮아
일단 다 읽은 것 같으니 이 이슈는 닫을게

그리고 #2 이슈 내용으로 간다
영어 문장이 해석이 안 되면 어디가 잘 모르겠는지 적어줘
